import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata = {
  title: "AM-IN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
